title: Eder Ignatowicz
author: Eder Ignatowicz
email: ignatowicz@gmail.com
description: >
  Eder Ignatowicz's Personal blog
baseurl: ""
url: "https://ederign.me"
google_analytics: "UA-119890893-1"
twitter_username: ederign
github_username: ederign
markdown: kramdown
permalink: pretty
exclude:
  - Gemfile*
  - Rakefile

disqus:
  shortname: ederign

plugins:
  - jekyll-feed

# --sunray: #edae49ff;
#--brick-red: #d1495bff;
# --metallic-seaweed: #00798cff;
#--lapis-lazuli: #30638eff;
#--indigo-dye: #003d5bff;

talks:
  - title: "The Multiplying Architecture2 "
    conference: "Kie Live"
    year: 2010
    color: "#d1495bff"
    file_name: "2013-javascript-the-right-way.pdf"

  - title: "The Multiplying Architecture"
    conference: "Kie Live"
    year: 2020
    color: "#edae49ff"
    link: "https://www.youtube.com/watch?v=Dvz0bGa9oh8"
