title: Eder Ignatowicz
author: Eder Ignatowicz
email: ignatowicz@gmail.com
description: >
  Eder Ignatowicz's Personal blog 
baseurl: ""
url: "https://ederign.me"
google_analytics: "UA-119890893-1"
twitter_username: ederign
github_username: ederign
markdown: kramdown
permalink: pretty
exclude:
  - Gemfile*
  - Rakefile

disqus:
  shortname: ederign

plugins:
  - jekyll-feed

talks:
  - title: "FIXME"
    conference: "FLISOL Campinas"
    year: 2013
    color: "#FBAA18"
    file_name: "2013-javascript-the-right-way.pdf"


